---

### Generic smell configuration

detectors:
  # You can disable smells completely
  IrresponsibleModule:
    enabled: false

  FeatureEnvy:
    exclude:
      - "ApiProxy::Middleware#call"

  Attribute:
    exclude:
      - "ApiProxy::Config"

  TooManyInstanceVariables:
    exclude:
      - "ApiProxy::Config"

  TooManyStatements:
    exclude:
      - "ApiProxy::Config"
